In [2]:
import numpy as np

In [3]:
my_nump=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(my_nump)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [4]:
#dimension
my_nump.ndim

2

In [5]:
#shape
my_nump.shape

(2, 5)

In [6]:
#type
my_nump.dtype

dtype('int32')

In [7]:
#itemsize
my_nump.itemsize

4

In [8]:
#nbytes
my_nump.nbytes

40

In [10]:
#indexing array
my_nump[1][2:]

array([8, 9, 0])

In [11]:
#slicing array
#[start:stop:step]
nmp=np.array(range(10))
print(nmp)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
nmp[0:6:2]

array([0, 2, 4])

In [13]:
#multidimension
my_nump[1:,2:]

array([[8, 9, 0]])

In [14]:
#reshaping array (dimensi harus n x n)
my_nump.reshape(5,2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [16]:
#joining array
my_nump=np.array([[1,2,3,4,5],[6,7,8,9,0]])
nmpy=np.array([[1,2,3,1,4],[2,3,5,3,5]])
np.concatenate([my_nump,nmpy])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 1, 4],
       [2, 3, 5, 3, 5]])

In [18]:
#objek pandas:Series vs dataframe
#series=onjek 1 dimensi, memiliki persamaan dengan list
import pandas as pd
x=pd.Series([6,3,4,6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64


In [19]:
#Series memiliki satu sumbu/index saja, dari contoh di atas sumbu/index tersebut berada satu baris, yaitu 0, 1, 2, 3. kita bisa mengubah sumbu/index tersebut dengan sebagai berikut
#cara pertama
x.index=['a','b','c','d']
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [21]:
#cara kedua
x=pd.Series([6,3,4,6],index=['a','b','c','d'])
print(x)

a    6
b    3
c    4
d    6
dtype: int64


In [22]:
print(type(x))

<class 'pandas.core.series.Series'>


In [23]:
#dataframe=objek 2 dimensir,memiliki 2 index, yaitu index baris dan index columns.
import pandas as pd
df=pd.DataFrame({'tipe_int':[50,21],'tipe_string':['a','b']})
print(df)

   tipe_int tipe_string
0        50           a
1        21           b


In [25]:
#import file
#dari csv
df_from_csv=pd.read_csv('rakamin_class.csv')
#dari excel
#df_from_excel=pd.read_excel('asasasas.xlsx')

In [26]:
#pemeriksaan sederhana karaketeristik data
#head()=secara default utk melihat 5 data pertama 
#tail()=secara default utk melihat 5 data terakhir 
df=pd.read_csv('rakamin_class.csv')

In [28]:
df.head(7)

registration_id    name              email      phone  age  \
0      RK20202344    Nina     nina@gmail.com  628198157   57   
1      RK20202345    Dyah     dyah@gmail.com  628306496   24   
2      RK20202346   Prima    prima@ymail.com  628755450   16   
3      RK20202347  Firman  firman@google.com  628638112   59   
4      RK20202348     Eva    eva@rakamin.com  628702735   42   
5      RK20202349   Bagus  bagus@hotmail.com  628816223   16   
6      RK20202350   Citra  citra@hotmail.com  628965407   36   

                              city        province  active  class  score  
0                    Tanjungpinang  Kepulauan Riau       1      6     80  
1                            Bogor      Jawa Barat       0      2     66  
2  Kota Administrasi Jakarta Pusat         Jakarta       1      1     55  
3                            Metro         Lampung       1      6     93  
4                           Malang      Jawa Timur       0      5     80  
5  Kota Administrasi Jakarta Pusat         Jakarta       1      1     84  
6                        Surakarta     Jawa Tengah       1      4     69

In [29]:
df.tail()

registration_id   name               email      phone  age          city  \
95      RK20202439  Abdul     abdul@gmail.com  628989064   54     Samarinda   
96      RK20202440    Ria       ria@gmail.com  628535849   56         Batam   
97      RK20202441  Putra     putra@gmail.com  628205046   51  Palangkaraya   
98      RK20202442  Kokom  kokom@facebook.com  628718477   23        Bekasi   
99      RK20202443  Ilham     ilham@gmail.com  628680755   29   Tasikmalaya   

             province  active  class  score  
95   Kalimantan Timur       0      6     59  
96     Kepulauan Riau       0      6     58  
97  Kalimantan Tengah       1      6     71  
98         Jawa Barat       0      2     73  
99         Jawa Barat       1      2     52

In [31]:
#info()=suatu method utk melakukan summary terhadap data
#yg memberikan informasi ttg tipe dari index data, tipe dari kolom data
#non-null values pada setiap kolom, dan jumlah memory
df=pd.DataFrame({'tipe_int':[50,21],'tipe_string':['a','b']})
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   tipe_int     2 non-null      int64 
 1   tipe_string  2 non-null      object
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [32]:
#describe()=utk menghasilkan kesimpulan deskriptif statistik dari data
df=pd.read_csv('rakamin_class.csv')

In [33]:
df.describe()

phone         age      active       class       score
count  1.000000e+02  100.000000  100.000000  100.000000  100.000000
mean   6.285217e+08   37.930000    0.640000    3.950000   74.770000
std    2.797442e+05   13.471448    0.482418    1.794351   13.561573
min    6.280073e+08   15.000000    0.000000    1.000000   50.000000
25%    6.283046e+08   26.750000    0.000000    2.000000   65.000000
50%    6.285330e+08   38.500000    1.000000    4.000000   74.000000
75%    6.287277e+08   50.250000    1.000000    6.000000   85.250000
max    6.289891e+08   59.000000    1.000000    6.000000  100.000000